In [1]:
import pandas as pd
import numpy as np

In [3]:

df = pd.read_csv('../files/coffe_sales - coffe_sales.csv')

In [4]:
df.head()

,hour_of_day,cash_type,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort,Date,Time
0,10,card,38.7,Latte,Morning,Fri,Mar,5,3,2024-03-01,10:15:51
1,12,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3,2024-03-01,12:19:23
2,12,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3,2024-03-01,12:20:18
3,13,card,28.9,Americano,Afternoon,Fri,Mar,5,3,2024-03-01,13:46:33
4,13,card,38.7,Latte,Afternoon,Fri,Mar,5,3,2024-03-01,13:48:15

In [5]:
df.isnull().sum()

hour_of_day    0
cash_type      0
money          0
coffee_name    0
Time_of_Day    0
Weekday        0
Month_name     0
Weekdaysort    0
Monthsort      0
Date           0
Time           0
dtype: int64

In [7]:
df.head()

,hour_of_day,cash_type,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort,Date,Time
0,10,card,38.7,Latte,Morning,Fri,Mar,5,3,2024-03-01,10:15:51
1,12,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3,2024-03-01,12:19:23
2,12,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3,2024-03-01,12:20:18
3,13,card,28.9,Americano,Afternoon,Fri,Mar,5,3,2024-03-01,13:46:33
4,13,card,38.7,Latte,Afternoon,Fri,Mar,5,3,2024-03-01,13:48:15

In [8]:
# practice get_dummies

In [11]:
a = pd.get_dummies(df,drop_first=True)

In [12]:
a = a.astype(int)

In [13]:
a.head(2)

,hour_of_day,money,Weekdaysort,Monthsort,coffee_name_Americano with Milk,coffee_name_Cappuccino,coffee_name_Cocoa,coffee_name_Cortado,coffee_name_Espresso,coffee_name_Hot Chocolate,...,Time_9:58:16,Time_9:58:30,Time_9:58:37,Time_9:59:02,Time_9:59:08,Time_9:59:11,Time_9:59:28,Time_9:59:40,Time_9:59:53,Time_9:59:56
0,10,38,5,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,12,38,5,3,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [14]:
#  encode with label encoder

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
lb = LabelEncoder()

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3547 entries, 0 to 3546
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   hour_of_day  3547 non-null   int64
 1   cash_type    3547 non-null   object
 2   money        3547 non-null   float64
 3   coffee_name  3547 non-null   object
 4   Time_of_Day  3547 non-null   object
 5   Weekday      3547 non-null   object
 6   Month_name   3547 non-null   object
 7   Weekdaysort  3547 non-null   int64
 8   Monthsort    3547 non-null   int64
 9   Date         3547 non-null   object
 10  Time         3547 non-null   object
dtypes: float64(1), int64(3), object(7)
memory usage: 304.9+ KB

In [18]:
df.head()

,hour_of_day,cash_type,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort,Date,Time
0,10,card,38.7,Latte,Morning,Fri,Mar,5,3,2024-03-01,10:15:51
1,12,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3,2024-03-01,12:19:23
2,12,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3,2024-03-01,12:20:18
3,13,card,28.9,Americano,Afternoon,Fri,Mar,5,3,2024-03-01,13:46:33
4,13,card,38.7,Latte,Afternoon,Fri,Mar,5,3,2024-03-01,13:48:15

In [20]:
df = df.drop(['Date', 'Time'], axis=1)

In [21]:
df.head(3)

,hour_of_day,cash_type,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort
0,10,card,38.7,Latte,Morning,Fri,Mar,5,3
1,12,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3
2,12,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3

In [22]:
df['cash_type'] = lb.fit_transform(df['cash_type'])
df['coffee_name'] = lb.fit_transform(df['coffee_name'])
df['Time_of_Day'] = lb.fit_transform(df['Time_of_Day'])
df['Weekday'] = lb.fit_transform(df['Weekday'])
df['Month_name'] = lb.fit_transform(df['Month_name'])

In [23]:
df.head(2)

,hour_of_day,cash_type,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort
0,10,0,38.7,7,1,0,7,5,3
1,12,0,38.7,6,0,0,7,5,3

In [24]:
# applying standardization

In [28]:
x = df.drop(columns = ['money'])
y = df['money']

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [31]:
np.round(x_train.describe(),2)

,hour_of_day,cash_type,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort
count,2837.00,2837.0,2837.00,2837.00,2837.00,2837.00,2837.00,2837.00
mean,14.16,0.0,3.18,0.99,3.01,6.01,3.83,6.45
std,4.23,0.0,2.59,0.82,2.04,3.39,1.96,3.50
min,6.00,0.0,0.00,0.00,0.00,0.00,1.00,1.00
25%,10.00,0.0,1.00,0.00,1.00,3.00,2.00,3.00
50%,14.00,0.0,2.00,1.00,3.00,7.00,4.00,7.00
75%,18.00,0.0,6.00,2.00,5.00,9.00,5.00,10.00
max,22.00,0.0,7.00,2.00,6.00,11.00,7.00,12.00

In [32]:
from sklearn.preprocessing import StandardScaler

In [33]:
sc = StandardScaler()

In [34]:
x_train_sc=sc.fit_transform(x_train)

In [35]:
x_train_new=pd.DataFrame(x_train_sc,columns=x_train.columns)

In [36]:
np.round(x_train_new.describe(),2)

,hour_of_day,cash_type,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort
count,2837.00,2837.0,2837.00,2837.00,2837.00,2837.00,2837.00,2837.00
mean,0.00,0.0,-0.00,0.00,-0.00,0.00,0.00,-0.00
std,1.00,0.0,1.00,1.00,1.00,1.00,1.00,1.00
min,-1.93,0.0,-1.23,-1.21,-1.47,-1.77,-1.44,-1.56
25%,-0.98,0.0,-0.84,-1.21,-0.98,-0.89,-0.93,-0.98
50%,-0.04,0.0,-0.46,0.02,-0.01,0.29,0.09,0.16
75%,0.91,0.0,1.09,1.24,0.97,0.88,0.60,1.01
max,1.85,0.0,1.47,1.24,1.46,1.48,1.61,1.58

In [37]:
# applying one Normalization

In [38]:
from sklearn.preprocessing import MinMaxScaler

In [39]:
mn = MinMaxScaler()

In [40]:
x_train_mn = mn.fit_transform(x_train)

In [41]:
x_train_new = pd.DataFrame(x_train_mn, columns = x_train.columns)

In [42]:
np.round(x_train_new.describe(),2)

,hour_of_day,cash_type,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort
count,2837.00,2837.0,2837.00,2837.00,2837.00,2837.00,2837.00,2837.00
mean,0.51,0.0,0.45,0.49,0.50,0.55,0.47,0.50
std,0.26,0.0,0.37,0.41,0.34,0.31,0.33,0.32
min,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00
25%,0.25,0.0,0.14,0.00,0.17,0.27,0.17,0.18
50%,0.50,0.0,0.29,0.50,0.50,0.64,0.50,0.55
75%,0.75,0.0,0.86,1.00,0.83,0.82,0.67,0.82
max,1.00,0.0,1.00,1.00,1.00,1.00,1.00,1.00

In [43]:
# filter for 30-40 indexed data

In [44]:
data = df.iloc[30:41]

In [45]:
data

,hour_of_day,cash_type,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort
30,9,0,38.7,7,1,5,7,2,3
31,14,0,38.7,7,0,5,7,2,3
32,17,0,38.7,7,2,5,7,2,3
33,17,0,38.7,6,2,5,7,2,3
34,17,0,38.7,3,2,5,7,2,3
35,17,0,38.7,6,2,5,7,2,3
36,17,0,38.7,6,2,5,7,2,3
37,17,0,28.9,4,2,5,7,2,3
38,18,0,38.7,6,2,5,7,2,3
39,13,0,28.9,0,0,6,7,3,3
40,13,0,28.9,4,0,6,7,3,3

In [46]:
# renaming of column

In [47]:
df = df.rename(columns={'money':'price','cash_type':'payment_method'})

In [48]:
df.head()

,hour_of_day,payment_method,price,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort
0,10,0,38.7,7,1,0,7,5,3
1,12,0,38.7,6,0,0,7,5,3
2,12,0,38.7,6,0,0,7,5,3
3,13,0,28.9,0,0,0,7,5,3
4,13,0,38.7,7,0,0,7,5,3