In [1]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer # For filling missing values
from sklearn.preprocessing import OneHotEncoder # For encoding categorical variables

from sklearn.preprocessing import OrdinalEncoder # For encoding categorical variables

In [2]:
df = pd.read_csv('../files/covid_toy - covid_toy.csv')

In [3]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [4]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(df.drop(columns = ['has_covid']), df['has_covid'], test_size = 0.2, random_state = 42)

In [5]:
x_train

    age  gender  fever   cough       city
55   81  Female  101.0    Mild     Mumbai
88    5  Female  100.0    Mild    Kolkata
26   19  Female  100.0    Mild    Kolkata
42   27    Male  100.0    Mild      Delhi
69   73  Female  103.0    Mild      Delhi
..  ...     ...    ...     ...        ...
60   24  Female  102.0  Strong  Bangalore
71   75  Female  104.0  Strong      Delhi
14   51    Male  104.0    Mild  Bangalore
92   82  Female  102.0  Strong    Kolkata
51   11  Female  100.0  Strong    Kolkata

[80 rows x 5 columns]

In [6]:
# adding simple imputer to fever column 
si = SimpleImputer(strategy = 'mean')
x_train_fever = si.fit_transform(x_train[['fever']])

# also the test datta 
x_test_fever = si.transform(x_test[['fever']])

x_train_fever.shape

(80, 1)

In [7]:
# ordinal encoding -- cough

oe = OrdinalEncoder(categories=[['Mild' , 'Strong']])
x_train_cough = oe.fit_transform(x_train[['cough']])

# also the test data
x_test_cough = oe.transform(x_test[['cough']])

x_train_cough.shape

(80, 1)

In [8]:
# onehotencoding -- gender city

ohe = OneHotEncoder(drop = 'first', sparse_output=False)
x_train_gender_city = ohe.fit_transform(x_train[['gender', 'city']])

# also the test data
x_test_gender_city = ohe.fit_transform(x_test[['gender', 'city']])

x_train_gender_city.shape

(80, 4)

In [9]:
# extracting age 
x_train_age = x_train.drop(columns = ['gender' , 'fever' , 'city' , 'cough']).values

# also the test data
x_test_age = x_test.drop(columns = ['gender' , 'fever' , 'city' , 'cough']).values

In [10]:
x_train_age.shape

(80, 1)

In [11]:
x_train_transformed = np.concatenate((x_train_age, x_train_fever,
                                     x_train_cough, x_train_gender_city), axis = 1)

In [12]:
x_train_transformed.shape

(80, 7)

by the help of column transformer

In [13]:
from sklearn.compose import ColumnTransformer

In [14]:
transformer = ColumnTransformer(transformers = [
    ('tnf1', SimpleImputer(), ['fever']),
    # help of SI we
    # fill missing values by mean, median , mode
    ('tnf2', OrdinalEncoder(categories=[['Mild' , 'Strong']]), ['cough']),
    # this process
    # we encode our data
    ('tnf3', OneHotEncoder(sparse_output = False , drop = 'first'),['gender','city'])
],remainder = 'passthrough')
# remainder = 'passthrough' means that the columns which are not mentioned in the transformers list will be passed through without any transformation.

In [15]:
transformer.fit_transform(x_train).shape

(80, 7)