In [2]:
                                      # DATA DIVIDATION:::
# Machine learning-----
# Data(50)----> x(input data),y(target_data)
# x-----> x_train,x_test
# y------> y_tarin,y_test
# for machine learninig we will pass (x_train,y_train)
# for machine testing (x_test)----> y_test

# 1+1=2
# 1+2=3
# 1+3=4
# 1+4=5
# 1+5=6
# 1+6=7


# x=(1+1,1+2,1+3,1+4,........,1+8)
# y=(2,3,5,7,8,9)
# x_train=(1+2,1+3,1+4,1+6)
# x_test=(1+7,1+8)
# y_train=(2,3,5,7)
# y_test=(8,9)

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("../files/covid_toy - covid_toy.csv")
df.head(3)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes
2   42   Male  101.0  Mild    Delhi        No

In [5]:
df.shape

(100, 6)

In [6]:
# df.isnull().sum()
df['fever']=df['fever'].fillna(df['fever'].mean())

In [7]:
x=df.drop(columns=['has_covid'])
x # inpuit data

    age  gender  fever   cough       city
0    60    Male  103.0    Mild    Kolkata
1    27    Male  100.0    Mild      Delhi
2    42    Male  101.0    Mild      Delhi
3    31  Female   98.0    Mild    Kolkata
4    65  Female  101.0    Mild     Mumbai
..  ...     ...    ...     ...        ...
95   12  Female  104.0    Mild  Bangalore
96   51  Female  101.0  Strong    Kolkata
97   20  Female  101.0    Mild  Bangalore
98    5  Female   98.0  Strong     Mumbai
99   10  Female   98.0  Strong    Kolkata

[100 rows x 5 columns]

In [8]:
x.shape

(100, 5)

In [9]:
y=df['has_covid']
y  # (target_data)

0      No
1     Yes
2      No
3      No
4      No
     ...
95     No
96    Yes
97     No
98     No
99    Yes
Name: has_covid, Length: 100, dtype: object

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [12]:
print("total data shape:",df.shape)
print("------------------------------")
print("Input data shpe:",x.shape)
print("x_train data shape:",x_train.shape)
print("x_test data shape:",x_test.shape)
print("-------------------------------")
print("target data shape:",y.shape)
print("y_train data shape:",y_train.shape)
print("y_test_data shape:",y_test.shape)

total data shape: (100, 6)
------------------------------
Input data shpe: (100, 5)
x_train data shape: (80, 5)
x_test data shape: (20, 5)
-------------------------------
target data shape: (100,)
y_train data shape: (80,)
y_test_data shape: (20,)

In [13]:
import pandas as pd

In [14]:
df=pd.read_csv("../EDA-Data-Analysis/files/placement - placement.csv")
df

    cgpa  resume_score  placed
0   8.14          6.52       1
1   6.17          5.17       0
2   8.27          8.86       1
3   6.88          7.27       1
4   7.52          7.30       1
..   ...           ...     ...
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

[100 rows x 3 columns]

In [15]:
df.shape

(100, 3)

In [16]:
x=df.drop(columns=['placed'])     # input data
x

    cgpa  resume_score
0   8.14          6.52
1   6.17          5.17
2   8.27          8.86
3   6.88          7.27
4   7.52          7.30
..   ...           ...
95  6.33          6.38
96  8.23          7.76
97  6.65          7.78
98  8.14          5.63
99  6.09          6.61

[100 rows x 2 columns]

In [17]:
y=df['placed'] #(target data)
y

0     1
1     0
2     1
3     1
4     1
     ..
95    0
96    1
97    0
98    1
99    0
Name: placed, Length: 100, dtype: int64

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [20]:
print("total data shape:",df.shape)
print("------------------------------")
print("Input data shpe:",x.shape)
print("x_train data shape:",x_train.shape)
print("x_test data shape:",x_test.shape)
print("-------------------------------")
print("target data shape:",y.shape)
print("y_train data shape:",y_train.shape)
print("y_test data shape:",y_test.shape)

total data shape: (100, 3)
------------------------------
Input data shpe: (100, 2)
x_train data shape: (80, 2)
x_test data shape: (20, 2)
-------------------------------
target data shape: (100,)
y_train data shape: (80,)
y_test data shape: (20,)