In [1]:
#encoding ---> converting categorical data into numerical data

In [2]:
# label encoding ---> has_covid['yes'/'no'] encode---> 1/0

In [3]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv("../files/covid_toy - covid_toy.csv")
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [5]:
df  = df.dropna()

In [6]:
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[90 rows x 6 columns]

In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
lb = LabelEncoder()

In [9]:
df['gender'] = lb.fit_transform(df['gender'])
df['has_covid'] = lb.fit_transform(df['has_covid'])
df['cough'] = lb.fit_transform(df['cough'])
df['city'] = lb.fit_transform(df['city'])

In [10]:
df

    age  gender  fever  cough  city  has_covid
0    60       1  103.0      0     2          0
1    27       1  100.0      0     1          1
2    42       1  101.0      0     1          0
3    31       0   98.0      0     2          0
4    65       0  101.0      0     3          0
..  ...     ...    ...    ...   ...        ...
95   12       0  104.0      0     0          0
96   51       0  101.0      1     2          1
97   20       0  101.0      0     0          0
98    5       0   98.0      1     3          0
99   10       0   98.0      1     2          1

[90 rows x 6 columns]

In [11]:
x = df.drop(columns=['has_covid'])
y = df['has_covid']

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
sc = StandardScaler()

In [17]:
x_train_sc = sc.fit_transform(x_train)

In [19]:
x_tarin_new = pd.DataFrame(x_train_sc,columns=x_train.columns)

In [21]:
np.round(x_tarin_new.describe(),2)

         age  gender  fever  cough   city
count  72.00   72.00  72.00  72.00  72.00
mean   -0.00   -0.00  -0.00   0.00   0.00
std     1.01    1.01   1.01   1.01   1.01
min    -1.53   -0.75  -1.30  -0.73  -1.20
25%    -0.95   -0.75  -0.83  -0.73  -1.20
50%     0.14   -0.75   0.13  -0.73  -0.24
75%     0.86    1.33   0.72   1.37   0.72
max     1.57    1.33   1.55   1.37   1.69