In [1]:
# wednesday(1/4/26)::
# Normal Distribution::>
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("../files/covid_toy - covid_toy.csv")
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [3]:
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [7]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [4]:
df['fever']=df['fever'].fillna(df['fever'].mean())

In [5]:
x=df.drop(columns=['city'])
x

    age  gender  fever   cough has_covid
0    60    Male  103.0    Mild        No
1    27    Male  100.0    Mild       Yes
2    42    Male  101.0    Mild        No
3    31  Female   98.0    Mild        No
4    65  Female  101.0    Mild        No
..  ...     ...    ...     ...       ...
95   12  Female  104.0    Mild        No
96   51  Female  101.0  Strong       Yes
97   20  Female  101.0    Mild        No
98    5  Female   98.0  Strong        No
99   10  Female   98.0  Strong       Yes

[100 rows x 5 columns]

In [8]:
df['gender']=df['gender'].map({"Male":0,"Female":1})
df['cough']=df['cough'].map({"Mild":0,"Strong":1})
df['has_covid']=df['has_covid'].map({"No":0,"Yes":1})

In [9]:
y=df['has_covid']
y

0     0
1     1
2     0
3     0
4     0
     ..
95    0
96    1
97    0
98    0
99    1
Name: has_covid, Length: 100, dtype: int64

In [10]:
df

    age  gender  fever  cough       city  has_covid
0    60       0  103.0      0    Kolkata          0
1    27       0  100.0      0      Delhi          1
2    42       0  101.0      0      Delhi          0
3    31       1   98.0      0    Kolkata          0
4    65       1  101.0      0     Mumbai          0
..  ...     ...    ...    ...        ...        ...
95   12       1  104.0      0  Bangalore          0
96   51       1  101.0      1    Kolkata          1
97   20       1  101.0      0  Bangalore          0
98    5       1   98.0      1     Mumbai          0
99   10       1   98.0      1    Kolkata          1

[100 rows x 6 columns]

In [11]:
x=df.drop(columns=['city'])

In [12]:
x

    age  gender  fever  cough  has_covid
0    60       0  103.0      0          0
1    27       0  100.0      0          1
2    42       0  101.0      0          0
3    31       1   98.0      0          0
4    65       1  101.0      0          0
..  ...     ...    ...    ...        ...
95   12       1  104.0      0          0
96   51       1  101.0      1          1
97   20       1  101.0      0          0
98    5       1   98.0      1          0
99   10       1   98.0      1          1

[100 rows x 5 columns]

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [15]:
np.round(x_train.describe(),2)

         age  gender   fever  cough  has_covid
count  80.00   80.00   80.00  80.00      80.00
mean   42.91    0.59  100.98   0.40       0.48
std    24.47    0.50    1.93   0.49       0.50
min     5.00    0.00   98.00   0.00       0.00
25%    20.00    0.00  100.00   0.00       0.00
50%    42.00    1.00  101.00   0.00       0.00
75%    65.00    1.00  102.00   1.00       1.00
max    84.00    1.00  104.00   1.00       1.00

In [16]:
from sklearn.preprocessing import StandardScaler

In [17]:
sc=StandardScaler()

In [18]:
x_train_sc=sc.fit_transform(x_train)    # fit means learn the parameter and transform means apply on that
x_train_new=pd.DataFrame(x_train_sc,columns=x_train.columns)

In [19]:
type(x_train_new)

pandas.core.frame.DataFrame

In [20]:
np.round(x_train_new.describe(),2)

         age  gender  fever  cough  has_covid
count  80.00   80.00  80.00  80.00      80.00
mean   -0.00   -0.00  -0.00  -0.00       0.00
std     1.01    1.01   1.01   1.01       1.01
min    -1.56   -1.19  -1.56  -0.82      -0.95
25%    -0.94   -1.19  -0.51  -0.82      -0.95
50%    -0.04    0.84   0.01  -0.82      -0.95
75%     0.91    0.84   0.53   1.22       1.05
max     1.69    0.84   1.57   1.22       1.05