In [2]:
# normalization ---> Using MinMaxScaling
# Data min_value = 0 , Max_value == 1

In [ ]:
# In this codition , if i apply any operation , then it will return huge number and
#we cannot make visualization because it will create a zig zag situation.

#

In [6]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('../files/covid_toy - covid_toy.csv')

In [6]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [7]:
df.dropna()

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[90 rows x 6 columns]

In [9]:
df  = df.drop(columns = ['city'])

In [10]:
df

    age  gender  fever   cough has_covid
0    60    Male  103.0    Mild        No
1    27    Male  100.0    Mild       Yes
2    42    Male  101.0    Mild        No
3    31  Female   98.0    Mild        No
4    65  Female  101.0    Mild        No
..  ...     ...    ...     ...       ...
95   12  Female  104.0    Mild        No
96   51  Female  101.0  Strong       Yes
97   20  Female  101.0    Mild        No
98    5  Female   98.0  Strong        No
99   10  Female   98.0  Strong       Yes

[100 rows x 5 columns]

In [ ]:
# --- step -- 1 :: Convert categorical data into numerical data

In [11]:
df['gender'] = df['gender'].map({'Male': 1, 'Female': 0})
df['cough'] = df['cough'].map({'Strong': 1, 'Mild': 0})
df['has_covid'] = df['has_covid'].map({'Yes': 1, 'No': 0})

In [12]:
df

    age  gender  fever  cough  has_covid
0    60       1  103.0      0          0
1    27       1  100.0      0          1
2    42       1  101.0      0          0
3    31       0   98.0      0          0
4    65       0  101.0      0          0
..  ...     ...    ...    ...        ...
95   12       0  104.0      0          0
96   51       0  101.0      1          1
97   20       0  101.0      0          0
98    5       0   98.0      1          0
99   10       0   98.0      1          1

[100 rows x 5 columns]

In [13]:
# --- step -- 2 :: Data devidation

In [14]:
x  = df.drop(columns = ['has_covid'])
y = df['has_covid']

In [15]:
# --- step -- 3 :: Normalization

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 42)

In [18]:
np.round(x_train.describe(),2)

         age  gender   fever  cough
count  80.00   80.00   71.00  80.00
mean   42.91    0.41  101.00   0.40
std    24.47    0.50    2.05   0.49
min     5.00    0.00   98.00   0.00
25%    20.00    0.00   99.50   0.00
50%    42.00    0.00  101.00   0.00
75%    65.00    1.00  103.00   1.00
max    84.00    1.00  104.00   1.00

In [19]:
from sklearn.preprocessing import MinMaxScaler

In [20]:
mn = MinMaxScaler()

In [21]:
x_train_mn = mn.fit_transform(x_train)

In [ ]:
x_train_new = pd.DataFrame(x_train_mn, columns = x_train.columns)

In [23]:
x_train_new

         age  gender     fever  cough
0   0.962025     0.0  0.500000    0.0
1   0.000000     0.0  0.333333    0.0
2   0.177215     0.0  0.333333    0.0
3   0.278481     1.0  0.333333    0.0
4   0.860759     0.0  0.833333    0.0
..       ...     ...       ...    ...
75  0.240506     0.0  0.666667    1.0
76  0.886076     0.0  1.000000    1.0
77  0.582278     1.0  1.000000    0.0
78  0.974684     0.0  0.666667    1.0
79  0.075949     0.0  0.333333    1.0

[80 rows x 4 columns]

In [24]:
np.round(x_train_new.describe(),2)

         age  gender  fever  cough
count  80.00   80.00  71.00  80.00
mean    0.48    0.41   0.50   0.40
std     0.31    0.50   0.34   0.49
min     0.00    0.00   0.00   0.00
25%     0.19    0.00   0.25   0.00
50%     0.47    0.00   0.50   0.00
75%     0.76    1.00   0.83   1.00
max     1.00    1.00   1.00   1.00

In [1]:
# ------ practice using placement data ------

In [13]:
df = pd.read_csv('../files/placement - placement.csv')

In [14]:
df.head()

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1
4  7.52          7.30       1

In [15]:
x = df.drop(columns = ['placed'])
y = df['placed']

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
x_test, x_train, y_test, y_train = train_test_split(x,y,test_size = 0.2, random_state = 42)

In [18]:
np.round(x_train.describe(),2)

        cgpa  resume_score
count  20.00         20.00
mean    6.91          6.65
std     1.12          0.81
min     5.47          5.44
25%     5.94          5.91
50%     6.65          6.72
75%     7.66          7.20
max     9.40          8.08

In [19]:
from sklearn.preprocessing import MinMaxScaler

In [20]:
mn = MinMaxScaler()

In [21]:
x_train_mn = mn.fit_transform(x_train)

In [22]:
x_train_new = pd.DataFrame(x_train_mn, columns = x_train.columns)

In [23]:
np.round(x_train_new.describe(),2)

        cgpa  resume_score
count  20.00         20.00
mean    0.37          0.46
std     0.28          0.31
min     0.00          0.00
25%     0.12          0.18
50%     0.30          0.48
75%     0.56          0.66
max     1.00          1.00