In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv("../files/insurance - insurance.csv")

In [3]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [5]:
df = df.drop(columns = 'region')

In [6]:
df.head()

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [7]:
# data conversion using label encoder 
from sklearn.preprocessing import LabelEncoder

In [8]:
le = LabelEncoder()

In [9]:
df['sex'] = le.fit_transform(df['sex'])
df['smoker'] = le.fit_transform(df['smoker'])

In [10]:
df.head()

   age  sex     bmi  children  smoker      charges
0   19    0  27.900         0       1  16884.92400
1   18    1  33.770         1       0   1725.55230
2   28    1  33.000         3       0   4449.46200
3   33    1  22.705         0       0  21984.47061
4   32    1  28.880         0       0   3866.85520

In [11]:
x = df.drop(columns = 'bmi')
y = df['bmi']

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 42)

In [14]:
np.round(x_train.describe(),2)

           age      sex  children   smoker   charges
count  1070.00  1070.00   1070.00  1070.00   1070.00
mean     39.36     0.51      1.11     0.21  13346.09
std      14.07     0.50      1.22     0.40  12019.51
min      18.00     0.00      0.00     0.00   1121.87
25%      27.00     0.00      0.00     0.00   4897.67
50%      39.50     1.00      1.00     0.00   9575.44
75%      51.00     1.00      2.00     0.00  16746.66
max      64.00     1.00      5.00     1.00  62592.87

In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
sc = StandardScaler()

In [17]:
x_train_sc = sc.fit_transform(x_train)

In [18]:
x_train_new = pd.DataFrame(x_train_sc,columns = x_train.columns)

In [20]:
np.round(x_train_new.describe(),2)

           age      sex  children   smoker  charges
count  1070.00  1070.00   1070.00  1070.00  1070.00
mean     -0.00    -0.00     -0.00     0.00     0.00
std       1.00     1.00      1.00     1.00     1.00
min      -1.52    -1.02     -0.91    -0.51    -1.02
25%      -0.88    -1.02     -0.91    -0.51    -0.70
50%       0.01     0.98     -0.09    -0.51    -0.31
75%       0.83     0.98      0.73    -0.51     0.28
max       1.75     0.98      3.20     1.97     4.10