In [1]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv("../files/insurance - insurance.csv")
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [11]:
x=df.drop(columns=["smoker","region"],inplace=True)

In [12]:
x

In [13]:
df

      age     sex     bmi  children      charges
0      19  female  27.900         0  16884.92400
1      18    male  33.770         1   1725.55230
2      28    male  33.000         3   4449.46200
3      33    male  22.705         0  21984.47061
4      32    male  28.880         0   3866.85520
...   ...     ...     ...       ...          ...
1333   50    male  30.970         3  10600.54830
1334   18  female  31.920         0   2205.98080
1335   18  female  36.850         0   1629.83350
1336   21  female  25.800         0   2007.94500
1337   61  female  29.070         0  29141.36030

[1338 rows x 5 columns]

In [14]:
df['sex'] = df['sex'].map({'male': 0, 'female': 1})

In [15]:
df

      age  sex     bmi  children      charges
0      19    1  27.900         0  16884.92400
1      18    0  33.770         1   1725.55230
2      28    0  33.000         3   4449.46200
3      33    0  22.705         0  21984.47061
4      32    0  28.880         0   3866.85520
...   ...  ...     ...       ...          ...
1333   50    0  30.970         3  10600.54830
1334   18    1  31.920         0   2205.98080
1335   18    1  36.850         0   1629.83350
1336   21    1  25.800         0   2007.94500
1337   61    1  29.070         0  29141.36030

[1338 rows x 5 columns]

In [16]:
y = df['charges']

In [17]:
y

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

In [18]:
df

      age  sex     bmi  children      charges
0      19    1  27.900         0  16884.92400
1      18    0  33.770         1   1725.55230
2      28    0  33.000         3   4449.46200
3      33    0  22.705         0  21984.47061
4      32    0  28.880         0   3866.85520
...   ...  ...     ...       ...          ...
1333   50    0  30.970         3  10600.54830
1334   18    1  31.920         0   2205.98080
1335   18    1  36.850         0   1629.83350
1336   21    1  25.800         0   2007.94500
1337   61    1  29.070         0  29141.36030

[1338 rows x 5 columns]

In [22]:
x = df.drop(columns = ['charges'])

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [25]:
np.round(x_train.describe(),2)

           age      sex      bmi  children
count  1070.00  1070.00  1070.00   1070.00
mean     39.36     0.49    30.56      1.11
std      14.07     0.50     6.04      1.22
min      18.00     0.00    15.96      0.00
25%      27.00     0.00    26.20      0.00
50%      39.50     0.00    30.21      1.00
75%      51.00     1.00    34.50      2.00
max      64.00     1.00    53.13      5.00

In [27]:
from sklearn.preprocessing import StandardScaler

In [28]:
sc = StandardScaler()

In [29]:
x_train_sc=sc.fit_transform(x_train)    # fit means learn the parameter and transform means apply on that
x_train_new=pd.DataFrame(x_train_sc,columns=x_train.columns)

In [30]:
x_train_new

           age       sex       bmi  children
0     0.472227  1.024602 -1.756525  0.734336
1     0.543313  1.024602 -1.033082 -0.911192
2     0.898745  1.024602 -0.943687 -0.911192
3    -0.025379  1.024602  0.622393  3.202629
4     1.040918  1.024602 -1.504893  1.557100
...        ...       ...       ...       ...
1065 -1.518194  1.024602  0.130717  2.379865
1066 -0.025379  1.024602 -1.107579  3.202629
1067  1.325264 -0.975989 -0.891539 -0.911192
1068 -0.167551  1.024602  2.820864  0.734336
1069  1.112004 -0.975989 -0.109327 -0.911192

[1070 rows x 4 columns]

In [31]:
np.round(x_train_new.describe(),2)

           age      sex      bmi  children
count  1070.00  1070.00  1070.00   1070.00
mean     -0.00    -0.00    -0.00     -0.00
std       1.00     1.00     1.00      1.00
min      -1.52    -0.98    -2.42     -0.91
25%      -0.88    -0.98    -0.72     -0.91
50%       0.01    -0.98    -0.06     -0.09
75%       0.83     1.02     0.65      0.73
max       1.75     1.02     3.74      3.20