In [1]:
import numpy as np 
import pandas as pd

In [ ]:
df=pd.read_csv("../files/tips - tips.csv")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [22]:
df.drop(columns=['day','time'])

     total_bill   tip     sex smoker  size
0         16.99  1.01  Female     No     2
1         10.34  1.66    Male     No     3
2         21.01  3.50    Male     No     3
3         23.68  3.31    Male     No     2
4         24.59  3.61  Female     No     4
..          ...   ...     ...    ...   ...
239       29.03  5.92    Male     No     3
240       27.18  2.00  Female    Yes     2
241       22.67  2.00    Male    Yes     2
242       17.82  1.75    Male     No     2
243       18.78  3.00  Female     No     2

[244 rows x 5 columns]

In [23]:
df['sex'] = df['sex'].map({'Male': 0, 'Female': 1})
df['smoker'] = df['smoker'].map({'No': 0, 'Yes': 1})

In [24]:
df

     total_bill   tip  sex  smoker   day    time  size
0         16.99  1.01    1       0   Sun  Dinner     2
1         10.34  1.66    0       0   Sun  Dinner     3
2         21.01  3.50    0       0   Sun  Dinner     3
3         23.68  3.31    0       0   Sun  Dinner     2
4         24.59  3.61    1       0   Sun  Dinner     4
..          ...   ...  ...     ...   ...     ...   ...
239       29.03  5.92    0       0   Sat  Dinner     3
240       27.18  2.00    1       1   Sat  Dinner     2
241       22.67  2.00    0       1   Sat  Dinner     2
242       17.82  1.75    0       0   Sat  Dinner     2
243       18.78  3.00    1       0  Thur  Dinner     2

[244 rows x 7 columns]

In [12]:
df.isnull().sum()

total_bill      0
tip             0
sex           244
smoker          0
day             0
time            0
size            0
dtype: int64

In [51]:
df.drop(columns = ['day','time'])

     total_bill   tip  sex  smoker  size
0         16.99  1.01    1       0     2
1         10.34  1.66    0       0     3
2         21.01  3.50    0       0     3
3         23.68  3.31    0       0     2
4         24.59  3.61    1       0     4
..          ...   ...  ...     ...   ...
239       29.03  5.92    0       0     3
240       27.18  2.00    1       1     2
241       22.67  2.00    0       1     2
242       17.82  1.75    0       0     2
243       18.78  3.00    1       0     2

[244 rows x 5 columns]

In [52]:
y =df['total_bill']
y

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [62]:
x = df.drop(columns=['total_bill','day','time'])

In [63]:
from sklearn.model_selection import train_test_split

In [64]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [65]:
np.round(x_train.describe(),2)

          tip     sex  smoker    size
count  195.00  195.00  195.00  195.00
mean     3.09    0.35    0.38    2.57
std      1.43    0.48    0.49    0.94
min      1.00    0.00    0.00    1.00
25%      2.00    0.00    0.00    2.00
50%      3.00    0.00    0.00    2.00
75%      3.70    1.00    1.00    3.00
max     10.00    1.00    1.00    6.00

In [66]:
from sklearn.preprocessing import StandardScaler

In [67]:
sc = StandardScaler()

In [68]:
x_train_sc=sc.fit_transform(x_train)  
x_train_new=pd.DataFrame(x_train_sc,columns=x_train.columns)

In [69]:
x_train_new

          tip       sex    smoker      size
0   -0.258033 -0.731733 -0.790569 -0.612141
1   -0.742114 -0.731733  1.264911 -0.612141
2    0.639973 -0.731733  1.264911 -0.612141
3    0.990757 -0.731733 -0.790569  1.519421
4   -0.742114 -0.731733 -0.790569 -0.612141
..        ...       ...       ...       ...
190  0.682067 -0.731733  1.264911 -0.612141
191 -0.047563  1.366619 -0.790569 -0.612141
192 -1.464729  1.366619  1.264911 -0.612141
193  0.324268 -0.731733  1.264911 -0.612141
194 -0.412378  1.366619  1.264911  0.453640

[195 rows x 4 columns]

In [70]:
np.round(x_train_new.describe(),2)

          tip     sex  smoker    size
count  195.00  195.00  195.00  195.00
mean    -0.00    0.00    0.00   -0.00
std      1.00    1.00    1.00    1.00
min     -1.46   -0.73   -0.79   -1.68
25%     -0.76   -0.73   -0.79   -0.61
50%     -0.06   -0.73   -0.79   -0.61
75%      0.43    1.37    1.26    0.45
max      4.85    1.37    1.26    3.65