In [6]:
import pandas as pd

In [12]:
df = pd.read_csv("covid_toy - covid_toy.csv")
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [13]:
# top data check , we will use df.head() , by default it returns top 5 rows 
df.head(5)

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [14]:
# bottom data check , we will use df.tail() , by default it gives last 5 rows 
df.tail(5)

    age  gender  fever   cough       city has_covid
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

In [38]:
# if you want random indexed data , then we will use df.sample(). By default it will return single row. 
df.sample()

    age  gender  fever  cough     city  has_covid
59    6       1  104.0    0.0  Kolkata          1

In [39]:
# if we want to check overall information then we will use df.info()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        100 non-null    int64
 1   gender     100 non-null    int64
 2   fever      100 non-null    float64
 3   cough      62 non-null     float64
 4   city       100 non-null    object
 5   has_covid  100 non-null    int64
dtypes: float64(2), int64(3), object(1)
memory usage: 4.8+ KB

In [1]:
# if we want to check data types of each column pf each use df.dtypes()
df.dtypes()

NameError: name 'df' is not defined

In [18]:
# if you want to check statical views of data , then you can use df.describe ()

In [19]:
df.describe()

              age       fever
count  100.000000   90.000000
mean    44.220000  100.844444
std     24.878931    2.054926
min      5.000000   98.000000
25%     20.000000   99.000000
50%     45.000000  101.000000
75%     66.500000  102.750000
max     84.000000  104.000000

In [20]:
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [21]:
# if you want to check missing data in df , then you will use df.isnull().sum()

In [24]:
df.isnull().sum() ## here fever has 10 missing values

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [25]:
# x = 1,2,3,NAN,5 
# mean = (1+2+3+4)/4 = 11/4 = 2.75
# we will this value in this missing data 
# x = 1,2,3,2.75,5

In [26]:
df['fever'] = df['fever'].fillna(df['fever'].mean())

In [28]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [29]:
df.head(1)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No

In [30]:
# if you caterigorical data, and you want to check total sub-categories then we will use df['column_name'].value_count()

In [31]:
df['gender'].value_counts()

gender
Female    59
Male      41
Name: count, dtype: int64

In [32]:
df['gender'] = df['gender'].map({"Female":1 , "Male":0})

In [33]:
df.head(5)

   age  gender  fever cough     city has_covid
0   60       0  103.0  Mild  Kolkata        No
1   27       0  100.0  Mild    Delhi       Yes
2   42       0  101.0  Mild    Delhi        No
3   31       1   98.0  Mild  Kolkata        No
4   65       1  101.0  Mild   Mumbai        No

In [34]:
df['cough'] =df['cough'].map({"Mild":0 , "Strond":1})

In [35]:
df.head(5)

   age  gender  fever  cough     city has_covid
0   60       0  103.0    0.0  Kolkata        No
1   27       0  100.0    0.0    Delhi       Yes
2   42       0  101.0    0.0    Delhi        No
3   31       1   98.0    0.0  Kolkata        No
4   65       1  101.0    0.0   Mumbai        No

In [36]:
df['has_covid'] = df['has_covid'].map({"No" : 0 , "Yes" : 1})

In [37]:
df.head(5)

   age  gender  fever  cough     city  has_covid
0   60       0  103.0    0.0  Kolkata          0
1   27       0  100.0    0.0    Delhi          1
2   42       0  101.0    0.0    Delhi          0
3   31       1   98.0    0.0  Kolkata          0
4   65       1  101.0    0.0   Mumbai          0

In [42]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [43]:
df['city'] = df['city'].map({"Kolkata":0 , "Bangalore":1 , "Delhi" : 3 , "Mumbai" : 4 })

In [44]:
df.head()

   age  gender  fever  cough  city  has_covid
0   60       0  103.0    0.0     0          0
1   27       0  100.0    0.0     3          1
2   42       0  101.0    0.0     3          0
3   31       1   98.0    0.0     0          0
4   65       1  101.0    0.0     4          0

In [14]:
df = pd.read_csv("tips - tips.csv")

In [16]:
df.head(5)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [21]:
df['sex'] = df['sex'].map({"Female" : 1 , "Male" : 0})

In [22]:
df.head(5)

   total_bill   tip  sex smoker  day    time  size
0       16.99  1.01  NaN     No  Sun  Dinner     2
1       10.34  1.66  NaN     No  Sun  Dinner     3
2       21.01  3.50  NaN     No  Sun  Dinner     3
3       23.68  3.31  NaN     No  Sun  Dinner     2
4       24.59  3.61  NaN     No  Sun  Dinner     4