In [1]:
# pandas ----> it is an open source library which is used for manage data manipulation.

In [3]:
# data structure of pandas :::::
# [1] Series --> it stores only values not column name and it is one dimensional.
# [2] DataFrame --> it stores values with column name, and it is multi dimentional.

In [1]:
import pandas as pd

In [4]:
a = pd.Series([1,2,3,4,50])
a

0     1
1     2
2     3
3     4
4    50
dtype: int64

In [5]:
type(a)

pandas.core.series.Series

DataFrame

In [11]:
a = {
    "Emp_id": [1,2,3,4,5],
    "Name" : ["Sam","Mohit","Raj","Rahul","Aniket"],
    "Department": ['IT','Sales','IT','IT','Sales'],
    "salary": [10000,20000,53000,26000,72000],
}

In [12]:
type(a)

dict

In [13]:
df = pd.DataFrame(a)
df

   Emp_id    Name Department  salary
0       1     Sam         IT   10000
1       2   Mohit      Sales   20000
2       3     Raj         IT   53000
3       4   Rahul         IT   26000
4       5  Aniket      Sales   72000

In [19]:
df.to_csv("emp_data.csv")
df

   Emp_id    Name Department  salary
0       1     Sam         IT   10000
1       2   Mohit      Sales   20000
2       3     Raj         IT   53000
3       4   Rahul         IT   26000
4       5  Aniket      Sales   72000

In [23]:
a = pd.read_csv("emp_data.csv")
a

   Unnamed: 0  Emp_id    Name Department  salary
0           0       1     Sam         IT   10000
1           1       2   Mohit      Sales   20000
2           2       3     Raj         IT   53000
3           3       4   Rahul         IT   26000
4           4       5  Aniket      Sales   72000

In [9]:
a = pd.read_csv("flipkart.csv")

In [5]:
# student id , student name, course, course duration , total fee
a = {
    "Student_id": [1,2,3,4,5,6,7,8,9,10],
    "Student_Name" : ["Sam","Mohit","Raj","Rahul","Aniket","Rajul","Sudhir","Nitesh","Manu","Manish"],
    "Course": ['IT','Sales','IT','IT','Sales','Data science','Java','Mern stack','IT','Sales'],
    "Course_Duration" : ['1 year','8 Months','8 Months','8 Months','7 Months','8 Months','9 Months','1.5 year','7.5 Months','1 year'],
    "Total_fees": [10000,20000,53000,26000,72000,50000,60000,20000,50000,40000],
}

In [6]:
df = pd.DataFrame(a)
df

   Student_id Student_Name        Course Course_Duration  Total_fees
0           1          Sam            IT          1 year       10000
1           2        Mohit         Sales        8 Months       20000
2           3          Raj            IT        8 Months       53000
3           4        Rahul            IT        8 Months       26000
4           5       Aniket         Sales        7 Months       72000
5           6        Rajul  Data science        8 Months       50000
6           7       Sudhir          Java        9 Months       60000
7           8       Nitesh    Mern stack        1.5 year       20000
8           9         Manu            IT      7.5 Months       50000
9          10       Manish         Sales          1 year       40000

In [19]:
df.to_csv("Student_data.csv")
df

   Student_id Student_Name        Course Course_Duration  Total_fees
0           1          Sam            IT          1 year       10000
1           2        Mohit         Sales        8 Months       20000
2           3          Raj            IT        8 Months       53000
3           4        Rahul            IT        8 Months       26000
4           5       Aniket         Sales        7 Months       72000
5           6        Rajul  Data science        8 Months       50000
6           7       Sudhir          Java        9 Months       60000
7           8       Nitesh    Mern stack        1.5 year       20000
8           9         Manu            IT      7.5 Months       50000
9          10       Manish         Sales          1 year       40000

In [17]:
df.to_excel("Students_data.xlsx")
df

   Student_id Student_Name        Course Course_Duration  Total_fees
0           1          Sam            IT          1 year       10000
1           2        Mohit         Sales        8 Months       20000
2           3          Raj            IT        8 Months       53000
3           4        Rahul            IT        8 Months       26000
4           5       Aniket         Sales        7 Months       72000
5           6        Rajul  Data science        8 Months       50000
6           7       Sudhir          Java        9 Months       60000
7           8       Nitesh    Mern stack        1.5 year       20000
8           9         Manu            IT      7.5 Months       50000
9          10       Manish         Sales          1 year       40000

In [21]:
a = pd.read_csv("tripadvisor.csv")
a

,biGQs,biGQs 2,evwcZ,biGQs 3,AVYYu,AVYYu 2,AVYYu 3,AVYYu 4
0,1. Jaypee Residency Manor,4.7,4.7 of 5 bubbles,"(3,137 reviews)",Romantic,Park View,Classic,Breakfast included
1,2. Hotel Vishnu Palace,4.5,4.5 of 5 bubbles,"(3,353 reviews)",Family,Modern,Business,Breakfast included
2,"3. Country Inn Premier Pacific Resort, Mussoorie",4.4,4.4 of 5 bubbles,(297 reviews),Romantic,Trendy,Business,NaN
3,4. Pride Ashiyana Resort Mussoorie,4.9,4.9 of 5 bubbles,(795 reviews),Romantic,Family,Quaint,Breakfast included
4,"5. Ramada by Wyndham,Mussoorie Mall Road",4.9,4.9 of 5 bubbles,"(1,940 reviews)",Romantic,Park View,Classic,Breakfast included
5,6. Hotel Mussoorie Heights,5.0,5 of 5 bubbles,(3 reviews),Quaint,Luxury,NaN,NaN
6,7. Sterling Mussoorie,4.7,4.7 of 5 bubbles,"(3,905 reviews)",Romantic,Trendy,Business,NaN
7,"8. Sangam By Stotrak, Jhula Ghar Mussoorie",5.0,5 of 5 bubbles,(73 reviews),Romantic,Budget,Family,NaN
8,9. Tulip Inn Green Castle - Hotel & Spa,3.9,3.9 of 5 bubbles,(331 reviews),Romantic,Modern,Family,NaN
9,10. Mosaic Hotel Mussoorie,4.8,4.8 of 5 bubbles,"(1,619 reviews)",Romantic,Boutique,Great View,Breakfast included
10,"11. The Hosteller Mussoorie, Mall Road",4.5,4.5 of 5 bubbles,(84 reviews),Romantic,Quaint,Charming,NaN
11,"12. The Fern Brentwood Resort Mussoorie, Serie...",4.8,4.8 of 5 bubbles,"(1,734 reviews)",Romantic,Classic,Trendy,Breakfast included
12,13. The Palm Aryan Mussoorie - A Boutique Hotel,4.5,4.5 of 5 bubbles,(26 reviews),Romantic,Boutique,Family,NaN
13,14. Madhuban Sarovar Portico Mussoorie,4.8,4.8 of 5 bubbles,"(1,234 reviews)",Romantic,City View,Family,NaN
14,15. Hotel Padmini Nivas,4.5,4.5 of 5 bubbles,(824 reviews),Romantic,Park View,Classic,NaN
15,"16. Lemon Tree Resort, Mussoorie",4.9,4.9 of 5 bubbles,(249 reviews),Romantic,Quaint,Business,Breakfast included
16,17. The Mountain Quail Hotel & Resort,4.7,4.7 of 5 bubbles,(533 reviews),Romantic,Trendy,Business,Breakfast included
17,18. Hotel Sungrace,4.8,4.8 of 5 bubbles,"(1,550 reviews)",Romantic,Classic,Trendy,Breakfast included
18,19. Treebo Raj Mall Road,5.0,5 of 5 bubbles,(6 reviews),Budget,Business,Quaint,NaN
19,"20. The Oasis Mussoorie, a member of Radisson ...",4.7,4.7 of 5 bubbles,"(2,393 reviews)",Romantic,Modern,Family,Breakfast included
20,21. JW Marriott Mussoorie Walnut Grove Resort ...,4.8,4.8 of 5 bubbles,"(4,209 reviews)",Romantic,Park View,Trendy,Breakfast included
21,"22. Hotel Paradise Mansion, Mussoorie",4.4,4.4 of 5 bubbles,(380 reviews),Romantic,Trendy,Family,Breakfast included
22,"23. Welcomhotel By ITC Hotels, The Savoy",4.9,4.9 of 5 bubbles,"(5,424 reviews)",Romantic,Park View,Classic,All inclusive
23,24. Zone Connect By The Park Mussoorie,4.5,4.5 of 5 bubbles,(821 reviews),Romantic,Trendy,Modern,NaN
24,25. Club Mahindra Mussoorie,4.8,4.8 of 5 bubbles,"(4,090 reviews)",Romantic,Family,Charming,NaN
25,26. Fortune Resort Grace - Mussoorie,4.8,4.8 of 5 bubbles,"(2,960 reviews)",Romantic,City View,Modern,Breakfast included
26,27. Mussoorie Gateway,4.1,4.1 of 5 bubbles,(464 reviews),Quiet,Trendy,Budget,NaN
27,"28. Tree of Life Highlands, Landour-Mussoorie",4.7,4.7 of 5 bubbles,(201 reviews),Romantic,Quaint,Mid-range,Breakfast included
28,29. Royal Orchid Fort Resort,4.8,4.8 of 5 bubbles,"(3,208 reviews)",Romantic,City View,Modern,NaN
29,30. Hotel Highland By DLS Hotels,4.7,4.7 of 5 bubbles,(445 reviews),Romantic,Boutique,Great View,Breakfast included