In [69]:
# what is d/f b/w series and data frame
# d/f b/w loc and iloc
# what is d/f b/w decribe and info
# what is d/f b/w head  tail sample
# how do u handle missing values using pandas
# how do you filter dat aby row and by column 
# what is group by perform operqation using group by 
# export your data into csv and excel format 
# how do you handle missing data in pandas
# how do you rename column 
# if you have two data frame in which a column is common no you have to merge these two dataframe into a singhlr dataframe 
# you have to update thye value of from 10-15 index number values all columns
# you have to convert categorical data into numerical data using map function

In [70]:
import pandas as pd

In [152]:
df = pd.read_csv('../files/covid_toy - covid_toy.csv')

In [121]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [145]:
# 1. difference b/w series and dataframe
# series :::: series is one dimensional array and i take only column as the input and output 
# data frame :::: dtaframe is two dimensinal array which took multiple column name and row values as input.

In [ ]:
# 2. diffrence b/w loc and iloc 
# loc :::  loc gives the output on the basis of the label of column name 
# iloc ::: iloc gives the output on the basis of the index number of the column \

In [96]:
df.loc[0 , 'gender']

'Male'

In [122]:
# 3. what is d/f b/w decribe and info
# describe ::: describe give the statical values of the data frame columns which consider min, max, std value etc.
# info ::: info gives the information about how many columns are there and dat types of column and also about the nulmvalues 
df.describe()

              age       fever
count  100.000000   90.000000
mean    44.220000  100.844444
std     24.878931    2.054926
min      5.000000   98.000000
25%     20.000000   99.000000
50%     45.000000  101.000000
75%     66.500000  102.750000
max     84.000000  104.000000

In [123]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        100 non-null    int64
 1   gender     100 non-null    object
 2   fever      90 non-null     float64
 3   cough      100 non-null    object
 4   city       100 non-null    object
 5   has_covid  100 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB

In [124]:
# 4. what is d/f b/w head  tail sample
# head gives the top values of the dataframe 
# df.head() : bydefault top five values 
# tail gives the last values of the dataframe
# df.tail() : bydefault last five values
# df.sample() : gives the random five values of the dataframe

In [125]:
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [126]:
df.tail(2)

    age  gender  fever   cough     city has_covid
98    5  Female   98.0  Strong   Mumbai        No
99   10  Female   98.0  Strong  Kolkata       Yes

In [127]:
df.sample()

    age  gender  fever cough    city has_covid
54   60  Female   99.0  Mild  Mumbai       Yes

In [128]:
# 5. how do u handle missing values using pandas
# missing values  are handled by using the :
# df.isnull().sum() : to check the null values
# df.dropna() : to drop the null values
# df.fillna() : to fill missing values with sum or mean

In [129]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [130]:
df.dropna()

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[90 rows x 6 columns]

In [131]:
df.fillna(df['fever'].mean())

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [132]:
# 6. how do you filter data by row and by column 
df['age'] = df['age'].where(df['age']>30 , other = 0)
df['age']

0     60
1      0
2     42
3     31
4     65
      ..
95     0
96    51
97     0
98     0
99     0
Name: age, Length: 100, dtype: int64

In [133]:
# 7. what is group by perform operqation using group by 
# groupby is used to group the data on the basis of aggregate fuction of another column values 
df.groupby('city')['fever'].mean()

city
Bangalore    100.964286
Delhi        100.800000
Kolkata      101.103448
Mumbai       100.076923
Name: fever, dtype: float64

In [109]:
# 8.. export your data into csv and excel format
# df.to_csv('filesource.csv') it is used for the opening csv file 
# df.to_excel('filesource.xlsx') it is used for the opening excel file

In [110]:
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1    0   Male  100.0  Mild    Delhi       Yes

In [112]:
# 9. how do you rename column 
df.rename(columns={'gender': 'sex'})

    age     sex  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1     0    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95    0  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97    0  Female  101.0    Mild  Bangalore        No
98    0  Female   98.0  Strong     Mumbai        No
99    0  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [158]:
# merging 
df_new  = pd.DataFrame({'city': ['Delhi', 'Mumbai']})

In [159]:
merg = pd.merge(df , df_new , on = 'city', how  = 'inner')

In [160]:
merg

    age  gender  fever   cough    city has_covid
0    27    Male  100.0    Mild   Delhi       Yes
1    42    Male  101.0    Mild   Delhi        No
2    65  Female  101.0    Mild  Mumbai        No
3    20  Female    NaN  Strong  Mumbai       Yes
4    64  Female  101.0    Mild   Delhi        No
5    75  Female    NaN    Mild   Delhi        No
6    65  Female   98.0    Mild  Mumbai       Yes
7    40  Female   98.0  Strong   Delhi        No
8    80  Female   98.0    Mild   Delhi       Yes
9    23    Male    NaN    Mild  Mumbai        No
10   33  Female  102.0  Strong   Delhi        No
11   34  Female    NaN  Strong  Mumbai       Yes
12   15    Male  101.0    Mild   Delhi       Yes
13   34  Female  101.0  Strong   Delhi       Yes
14   74    Male  102.0    Mild  Mumbai       Yes
15   49  Female  101.0    Mild   Delhi       Yes
16   49  Female  102.0    Mild   Delhi        No
17   27    Male  100.0    Mild   Delhi       Yes
18   20    Male  102.0  Strong   Delhi        No
19   19  Female  101.0    Mild  Mumbai        No
20   44    Male  104.0    Mild  Mumbai        No
21   19    Male  101.0    Mild   Delhi       Yes
22   83    Male   98.0    Mild   Delhi       Yes
23   60  Female   99.0    Mild  Mumbai       Yes
24   81  Female  101.0    Mild  Mumbai       Yes
25   23    Male   98.0  Strong  Mumbai       Yes
26   81  Female   98.0  Strong  Mumbai        No
27   42    Male  104.0    Mild  Mumbai        No
28   73  Female  103.0    Mild   Delhi        No
29   68  Female  101.0  Strong   Delhi        No
30   75  Female  104.0  Strong   Delhi        No
31   34  Female  104.0  Strong   Delhi        No
32   14  Female   99.0    Mild  Mumbai       Yes
33   65    Male   99.0    Mild   Delhi        No
34   69  Female   98.0  Strong  Mumbai        No
35   59  Female   99.0  Strong   Delhi        No
36   38    Male    NaN    Mild   Delhi       Yes
37    5  Female   98.0  Strong  Mumbai        No

In [89]:
# 11 you have to update the values from 10 to 50 index no values of all columns

df.loc[10:50] = 100

In [90]:
df

   a  b
0  0  a
1  0  a
2  0  c
3  4  d
4  5  e

In [137]:
# map function 
df['gender']=df['gender'].map({"Male":0,"Female":1})
df['cough']=df['cough'].map({"Mild":0,"Strong":1})
df['has_covid']=df['has_covid'].map({"No":0,"Yes":1})

In [143]:
df = df.drop(columns = ['city'])

In [144]:
df

    age  gender  fever  cough  has_covid
0    60       0  103.0      0          0
1     0       0  100.0      0          1
2    42       0  101.0      0          0
3    31       1   98.0      0          0
4    65       1  101.0      0          0
..  ...     ...    ...    ...        ...
95    0       1  104.0      0          0
96   51       1  101.0      1          1
97    0       1  101.0      0          0
98    0       1   98.0      1          0
99    0       1   98.0      1          1

[100 rows x 5 columns]